### ISSUE TITLE
Update Winapp2.ini

### ISSUE THREAD

**Issue by Debeet** [bmrf/tron#107]
It was updated last 10 months ago, if I assume correctly from GitHub. Maybe it's time to update it and enable more cleaning in ccleaner.ini?

https://github.com/moscadotto/winapp2

**Comment by vocatus** [comment]
I'm hesistant to update it because we've manually disabled quite a few things (Sticky Notes, Steam DepotCache, Pinned Taskbar Items, etc) and it takes quite a while to hunt through the new file and turn them all back off again. 

Could you compare Tron's changelog (search for any occurrence of `winapp2`) and update the latest winapp2 with our changes?

**Comment by vocatus** [comment]
Hi @Debeet, since I don't have time to do this myself and no one has volunteered to build the new file I'm closing this.
