### ISSUE TITLE
[Suggestion] add "Bulk Crap Uninstaller"

### ISSUE THREAD

**Issue by n1trux** [bmrf/tron#116]
I've been using this program in the past for manual removal of Crapware and unneeded programs.

In my opinion it would be nice if BCUninstaller would be in the manual tools folder so other people can enjoy using it as well.

>Bulk Crap Uninstaller (or BCUninstaller) is a free (as in speech) program uninstaller. It excels at removing large amounts of applications with minimal user input. It can clean up leftovers, detect orphaned applications, run uninstallers according to premade lists, and much more! Even though BCU was made with IT pros in mind, by default it is so straight-forward that anyone can use it.
>BCU is fully compatible with Windows Store Apps, Steam, Windows Features and has special support for many uninstalling systems (NSIS, InnoSetup, Msiexec, and many other).

Link: https://github.com/Klocman/Bulk-Crap-Uninstaller

**Comment by kronflux** [comment]
Personally, and this is just my opinion, I don't think it's really necessary to include. Firstly, Tron does many removals of crapware already(and the stuff it doesn't remove can easily be added to the removals, if you can provide the uninstaller location or the GUID)

Secondly, this would just be among the average technician's personal arsenal of tools. Since Tron wouldn't be running it itself at any point, and it's not part of the current usage process of Tron, I don't think it needs to be included.

If every tool that's useful to techs was included along with Tron, the list would be very large. xD

**Comment by vocatus** [comment]
I haven't heard of this utility but will take a look at it. Anything that can assist in automating bloat removal is a candidate for inclusion, providing it doesn't duplicate functionality of course. Open to hearing anyone else's thoughts as well.

**Comment by vocatus** [comment]
OK, after looking it over, I really like BCU, seems very powerful. However, since it's not automatable, I'm going to leave it out of Tron for now and close this suggestion. Thanks for the recommendation.
