### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by dbucci24** [bmrf/tron#127]
Hello, I would like to collaborate with the Spanish translation, is it done?

**Comment by vocatus** [comment]
Hi @dbucci24 , thanks for asking. We don't currently have a Spanish translation of Tron. Are you wanting to translate the [readme](https://github.com/bmrf/tron/blob/master/README.md) or the entire project? It might be tricky to do the entire project since it updates fairly often, but a Spanish readme would be very helpful.

**Comment by dbucci24** [comment]
Yes, I would like to translate the readme file! And then if you need to translate the rest of the project!

**Comment by vocatus** [comment]
That's great! If you do a pull request and submit the translated Readme I'll be happy to post it. As for translating the rest of the project (mostly log messages I'm assuming) just keep in mind I can't keep the translation updated since my Spanish is pretty bad, so you'll have to refresh the translation when new Tron versions come out if you want to maintain a Spanish-language version. I'll close this issue and wait to hear from you with the updated files. Thanks!
