### ISSUE TITLE
Browsing History and Last Activity [Enhancement]

### ISSUE THREAD

**Issue by bsisco** [bmrf/tron#132]
After using tron a few times I've come to the conclusion that it would be nice to be able to pull the browser histories (via nirsoft's [browsinghistoryview.exe](https://www.nirsoft.net/utils/browsing_history_view.html)) and the last activity (via [lastactivityview.exe](https://www.nirsoft.net/utils/computer_activity_view.html)) from the machine before clearing them out in stage 1. These could/would be helpful in determining if the issue is due to bad user habits that require some retraining or some other nefarious activity.

**Comment by vocatus** [comment]
Hi @bsisco , I agree that's a good idea to run, however since it's a little bit of a niche task (most people just run and don't really care what was happening before), I'm going to leave it out of Tron for now. My suggestion would be to just run it prior to running Tron if you think malware/bad habits might be the case.
