### ISSUE TITLE
Flag to skip removing duplicate files

### ISSUE THREAD

**Issue by Michael-Bell** [bmrf/tron#147]
Basically I'd like a flag to forbid Stage 1 steps 4/6 to remove anything inside the C:\Users directory. I'm not sure if it's best to just have a flag to just skip the entire thing, or if it's worth having ability to choose 
- Downloads 
- Internet Browser
- Windows Updates
- And so on...

Thanks,
Michael

**Comment by Michael-Bell** [comment]
When I'm working on a users computer, I don't want anything except myself deleting files or folders inside the users personal directory. 2 reasons for this:

If the customer comes back in a few days and says I deleted the photo of their cat's funeral or the pirated game their friend shared with them, I need to know exactly what they are talking about. 

Also some users may download self contained programs like "PortableApps" and extract them to the downloads folder since the installer usually defaults to there....
For example:
1. go to https://dl.slic3r.org/dev/win/
2. Download and extract the 2 or 3 most recent builds and extract them to your downloads folder
3. Run Tron
4. Tron will detect most of the images linked in each folder are binary identical and will delete 1 or 2 copies of the image.
4. Open each instance of slic3r and open a few menus
5. Program will crash

You can obviously go back and restore the files, but it's a bit annoying. 

I have a similar problem with the way Tron handles browser profiles. As it is right now it will delete the files that keep you logged into sites. While it's not necessarily bad, it is annoying from the user's perspective because they would now need to find their password diary and figure out which password to use.

**Comment by vocatus** [comment]
To your first point, Tron saves a full file list of every single file on the system before and after the run. These are kept in the RAW_LOGS folder (`c:\logs\tron\raw_logs\` by default), so you can prove you didn't delete some file if that issue comes up.

As far as nuking duplicate files in the Downloads folder, hmmm. This is similar in my mind to a user who complained we shouldn't empty the recycle bin because he kept files there. Unfortunately, the point of the recycle bin is to put files for deletion, and not a safe place to keep them. Ultimately I declined the request because it didn't make sense to change something that works for 95% of people for one person doing things an odd way. 

Additionally, Tron is meant as a system recovery tool, not something for routine maintenance, so after some debate in the community we ended up keeping the full browser wipe and reset, since we also notify in bright red text at the beginning that Tron will wipe the browser cache+cookies. 

I may be open to adding a switch for skipping Downloads cleanup, but it tends to be a beneficial thing for most users. Would you mind making a poll thread on the subreddit and see how much interest there is for adding it? 

Of course (as you know) you can easily delete/disable that part of the code prior to running, but I do understand that would get annoying over multiple version updates.

**Comment by qwertychouskie** [comment]
IMO there should be some sort of "PC Technician" flag that disables clearing duplicate files, the Recycle Bin, the browser history, etc.

**Comment by vocatus** [comment]
@Michael-Bell @qwertychouskie would either of you mind throwing up a post on the subreddit to get feedback? I'm not opposed to adding a switch for that but only if there's a decent amount of support for it. I try to avoid adding switches for every little thing (code complexity) but if enough people would find it useful I'm open to it.
