### ISSUE TITLE
Why do we have to kill solitaire.exe after 20 minutes? Can't tron do it by its own?

### ISSUE THREAD

**Issue by ArmeF97** [bmrf/tron#159]
Why do we have to kill solitaire.exe after 20 minutes? Can't tron do it by its own?
Can't it create a new process to do so? Wait 20 minutes than kill

**Comment by vocatus** [comment]
"Solitaire" is really rkill, an anti-malware tool. It automatically exists when it finishes its scan. However, sometimes it hangs, hence the message. The reason we can't kill automatically is there's really no way to tell if it's _hung_ or just slow on a particular system.

**Comment by ArmeF97** [comment]
And how about providing an option, is selected, that kills it after 20 minutes?

**Comment by vocatus** [comment]
@ArmeF97 we could do that, but again the issue is that sometimes it just takes a really long time, but isn't actually hung. I've gone back and forth on how to handle it a few times, and eventually just kind of landed on printing that message and leaving it up to the user if they think it's truly hung or not.

**Comment by ZaidHAROON** [comment]
Ya there is a Thing If the job takes More than 20 minutes Kill Solitaire.exe with task manager
So around 30 mins have been passed So what does that mean and how to do it?
Suggestions are welcome...
