### ISSUE TITLE
[REQUEST] Make sfc scannow optional

### ISSUE THREAD

**Issue by ptrkhh** [bmrf/tron#163]
From my experience, sfc scannow is one of the most time consuming part of this script, and for those who uses this script on a new Windows install, it is not necessary to use sfc scannow as the Windows OS was just completely installed beforehand.

EDIT: Also the /scanhealth

**Comment by piksu** [comment]
Referring to this? 
- https://github.com/bmrf/tron/blob/8fbcb82b54aaaf8aa856c076395a8c26049994aa/resources/stage_4_repair/stage_4_repair.bat#L116

**Comment by ptrkhh** [comment]
Yes, precisely.

Iirc there's also scanhealth somewhere after that (not sure though), it's also time consuming

**Comment by vocatus** [comment]
I thought over this for a bit, and I think because the purpose of Tron is to repair/rescue infected or sluggish systems, and the [development philosophy of the project](https://www.reddit.com/r/TronScript/wiki/index#wiki_3._tron_is_slow) is "more time to do it right vs. less time and be less thorough" I'm going to leave it in as a default. Of course, you can always just delete that block of code in your copy of Tron and it'll be skipped entirely.

One additional thing to note, I understand a lot of people use Tron to de-bloat a fresh Windows install, is each sub-stage script supports standalone execution, so you can just manually run the Stage 2 and Stage 4 (the two most popular stages) scripts on a fresh system.
