### ISSUE TITLE
programs_to_target_by_GUID.bat throwing The system cannot find the path specified error

### ISSUE THREAD

**Issue by wakeboard143** [bmrf/tron#28]
On line 1046 shouldn't the command be:
if /i %DRY_RUN%==no call resources\stage_2_de-bloat\oem\programs_to_target_by_GUID.bat >> "%LOGPATH%\%LOGFILE%" 2>&1

where the current line reads:
if /i %DRY_RUN%==no call stage_2_de-bloat\oem\programs_to_target_by_GUID.bat >> "%LOGPATH%\%LOGFILE%" 2>&1

**Comment by vocatus** [comment]
No, because in lines [242-243](https://github.com/bmrf/tron/blob/27219e6fcc76c6eac8892461d44af324edb4ee03/tron.bat#L242-L243) we pushd into the resources directory, so we're still sitting there by the time we get to line 1046.

The error came from a command to delete a file that didn't exist, in the programs_to_target_by_GUID.bat file, which I fixed this morning. Thanks
