### ISSUE TITLE
Tron should have a "Identity" Disc script

### ISSUE THREAD

**Issue by RedBaron2** [bmrf/tron#96]
@vocatus 
I believe that like all good "programs" Tron should have a "Identity" Disc. This can be a script of frequently used 'tools' that Tron can use to fight for the Users.
One such 'tool' could be:
`:: Pause X`
`:tron_wait_x`
`ping -n %1 localhost >nul`
`goto :EOF`

This could be called from the different batch files.
Instead of having in the script
`ping 127.0.0.1 -n 180 > nul 2>&1`
you could have
`call "functions\tron_disc.bat" tron_wait_x 180`

Another tool could be determining "Bitness" of the system. 
`Set "_Bitness=64"`
`IF "%PROCESSOR_ARCHITECTURE%" == "x86" (`
`IF NOT DEFINED PROCESSOR_ARCHITEW6432 Set "_Bitness=32" )`

Then all scripts that require the information could just check for the "%_Bitness%" variable.

**Comment by vocatus** [comment]
Thanks for the suggestions @RedBaron2. Many of the things you mentioned are already implemented in Tron in one form or another. For example:

1. "Pause" command or similar - I don't really see a benefit to creating another sub-script just to embed the `ping` command in it, since we can just call `ping` directly from anywhere already.

2. Determining bitness of the system - again something I don't see any benefit to creating another script or function for. The `%PROCESSOR_ARCHITECTURE%` variable is a system variable and present on every Windows system already; what benefit would we gain by creating another variable that, more or less, duplicates the information already contained there?

**Comment by RedBaron2** [comment]
@vocatus 

> I don't really see a benefit to creating another sub-script just to embed the ping command in it, since we can just call ping directly from anywhere already.

I could make the same argument for your use of echo in the log.bat file. I will just agree to disagree at this time, and close this issue.
